import { TestData } from "./types";

declare global {
  interface Window {
    jspdf: any;
  }
}

export const generatePDF = (testData: TestData, customSubtitle?: string, examName?: string, watermarkText?: string, watermarkOpacity: number = 0.1) => {
  const jsPDF = window.jspdf.jsPDF;
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let yPos = 20;

  const PRIMARY_COLOR = [8, 145, 178]; // Cyan 600
  const TEXT_COLOR = [15, 23, 42];     // Slate 900
  const SUB_TEXT_COLOR = [100, 116, 139]; // Slate 500

  const drawLogo = (x: number, y: number, size: number) => {
    doc.setDrawColor(...PRIMARY_COLOR);
    doc.setLineWidth(0.4);
    doc.circle(x, y, size, 'S'); 
    doc.circle(x, y, size * 0.7, 'S'); 
    doc.line(x - size, y, x + size, y);
    doc.line(x, y - size, x, y + size);
    doc.setFillColor(...PRIMARY_COLOR);
    doc.circle(x, y, 1.5, 'F');
  };

  const drawStudentHeader = () => {
    // Top Branding
    drawLogo(margin + 6, 22, 6);
    drawLogo(pageWidth - margin - 6, 22, 6);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...PRIMARY_COLOR);
    doc.text("Study.AI Test Generator", pageWidth / 2, 15, { align: 'center' });
    
    // Configurable Exam Name - Prominent
    let currentY = 22;
    if (examName) {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(18); // Larger font for prominence
        doc.setTextColor(0, 0, 0);
        doc.text(examName.toUpperCase(), pageWidth / 2, currentY, { align: 'center' });
        currentY += 7;
    }

    const subText = customSubtitle || `Generated: ${new Date().toLocaleDateString()}`;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...SUB_TEXT_COLOR);
    doc.text(subText, pageWidth / 2, currentY, { align: 'center' });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    
    const startY = currentY + 15;
    doc.text("Name:", margin, startY);
    doc.line(margin + 15, startY, margin + 85, startY);
    
    doc.text("Roll No:", pageWidth - margin - 60, startY);
    doc.line(pageWidth - margin - 45, startY, pageWidth - margin, startY);

    return startY + 12;
  };

  const addWatermark = () => {
    const textToPrint = watermarkText || examName || "Study.AI";
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.saveGraphicsState();
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text("Generated by Study.AI", margin, pageHeight - 10);
      doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin, pageHeight - 10, { align: "right" });
      
      // Configurable Watermark
      doc.setTextColor(200, 200, 200);
      doc.setFontSize(50);
      doc.setFont("helvetica", "bold");
      if (doc.setGState) {
        doc.setGState(new doc.GState({ opacity: watermarkOpacity }));
      }
      doc.text(textToPrint, pageWidth / 2, pageHeight / 2, {
        align: 'center',
        angle: 45,
        baseline: 'middle'
      });
      doc.restoreGraphicsState();
    }
  };

  const checkPageBreak = (neededSpace: number) => {
    if (yPos + neededSpace > pageHeight - margin) {
      doc.addPage();
      yPos = margin + 10;
    }
  };

  yPos = drawStudentHeader();
  
  doc.setFillColor(...PRIMARY_COLOR);
  doc.rect(0, yPos, pageWidth, 1.5, 'F');
  yPos += 15;

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...TEXT_COLOR);
  const splitTitle = doc.splitTextToSize(testData.title, pageWidth - (margin * 2));
  doc.text(splitTitle, margin, yPos); 
  yPos += (splitTitle.length * 7) + 5;

  if (testData.subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(...SUB_TEXT_COLOR);
    doc.text(testData.subtitle, margin, yPos);
    yPos += 10;
  }
  
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.1);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 15;

  const renderSectionHeader = (title: string) => {
      checkPageBreak(25);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(...PRIMARY_COLOR);
      doc.text(title, margin, yPos);
      yPos += 10;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(...TEXT_COLOR);
  };

  // I. MCQs
  if (testData.mcqs?.length > 0) {
    renderSectionHeader("I. MULTIPLE CHOICE");
    testData.mcqs.forEach((mcq, index) => {
      checkPageBreak(35);
      doc.setFont("helvetica", "bold");
      const questionText = `${index + 1}. ${mcq.question}`;
      const splitQuestion = doc.splitTextToSize(questionText, pageWidth - (margin * 2));
      doc.text(splitQuestion, margin, yPos);
      yPos += (splitQuestion.length * 5) + 3;

      doc.setFont("helvetica", "normal");
      mcq.options.forEach((opt, i) => {
        const optText = `   ${String.fromCharCode(65 + i)}) ${opt}`;
        const splitOpt = doc.splitTextToSize(optText, pageWidth - (margin * 2));
        doc.text(splitOpt, margin, yPos);
        yPos += (splitOpt.length * 5) + 1;
      });
      yPos += 5;
    });
    yPos += 5;
  }

  // II. True/False
  if (testData.trueFalse?.length > 0) {
    renderSectionHeader("II. TRUE OR FALSE");
    testData.trueFalse.forEach((tf, index) => {
      checkPageBreak(20);
      const text = `${index + 1}. ${tf.statement}`;
      const splitText = doc.splitTextToSize(text, pageWidth - (margin * 2) - 30);
      doc.text(splitText, margin, yPos);
      doc.text("[ T ]   [ F ]", pageWidth - margin - 30, yPos);
      yPos += (splitText.length * 5) + 5;
    });
    yPos += 5;
  }

  // III. Fill in Blanks
  if (testData.fillInBlanks?.length > 0) {
    renderSectionHeader("III. FILL IN THE BLANKS");
    testData.fillInBlanks.forEach((fib, index) => {
      checkPageBreak(25);
      const text = `${index + 1}. ${fib.sentence}`;
      const splitText = doc.splitTextToSize(text, pageWidth - (margin * 2));
      doc.text(splitText, margin, yPos);
      yPos += (splitText.length * 5) + 8; // Extra space for writing
    });
    yPos += 5;
  }

  // IV. Matching
  if (testData.matching?.length > 0 && testData.matching[0].pairs.length > 0) {
    renderSectionHeader("IV. MATCHING");
    
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...TEXT_COLOR);
    doc.text("Column A", margin, yPos);
    doc.text("Column B", pageWidth / 2 + 10, yPos);
    yPos += 8;

    doc.setFont("helvetica", "normal");
    const pairs = testData.matching[0].pairs;
    const colB = [...pairs].sort(() => Math.random() - 0.5);

    pairs.forEach((pair, index) => {
      checkPageBreak(15);
      const textA = `${index + 1}. ${pair.item}`;
      const splitA = doc.splitTextToSize(textA, (pageWidth/2) - margin - 5);
      
      const textB = `${String.fromCharCode(65 + index)}. ${colB[index].match}`;
      const splitB = doc.splitTextToSize(textB, (pageWidth/2) - margin - 5);

      const maxLines = Math.max(splitA.length, splitB.length);
      
      doc.text(splitA, margin, yPos);
      doc.text(splitB, pageWidth / 2 + 10, yPos);
      
      yPos += (maxLines * 5) + 4;
    });
    yPos += 5;
  }

  // V. Short Questions
  if (testData.shortQuestions?.length > 0) {
    renderSectionHeader("V. SHORT ANSWER");
    testData.shortQuestions.forEach((sq, index) => {
      checkPageBreak(40);
      const text = `${index + 1}. ${sq.question}`;
      const splitText = doc.splitTextToSize(text, pageWidth - (margin * 2));
      doc.text(splitText, margin, yPos);
      yPos += (splitText.length * 5) + 30; // Space for answer
    });
  }

  // VI. Long Questions
  if (testData.longQuestions?.length > 0) {
    renderSectionHeader("VI. LONG ANSWER");
    testData.longQuestions.forEach((lq, index) => {
      checkPageBreak(80);
      const text = `${index + 1}. ${lq.question}`;
      const splitText = doc.splitTextToSize(text, pageWidth - (margin * 2));
      doc.text(splitText, margin, yPos);
      yPos += (splitText.length * 5) + 5;
      
      doc.setDrawColor(220, 220, 220);
      doc.setLineWidth(0.1);
      for(let l=0; l<10; l++) {
          doc.line(margin, yPos, pageWidth - margin, yPos);
          yPos += 8;
      }
      yPos += 8;
    });
  }

  // VII. Essays
  if (testData.essays?.length > 0) {
    renderSectionHeader("VII. ESSAY");
    testData.essays.forEach((eq, index) => {
      checkPageBreak(100); 
      const text = `${index + 1}. ${eq.question}`;
      const splitText = doc.splitTextToSize(text, pageWidth - (margin * 2));
      doc.text(splitText, margin, yPos);
      yPos += (splitText.length * 5) + 5;
      
      doc.setDrawColor(220, 220, 220);
      doc.setLineWidth(0.1);
      for(let l=0; l<15; l++) {
          doc.line(margin, yPos, pageWidth - margin, yPos);
          yPos += 8;
      }
      yPos += 8;
    });
  }

  // ANSWER KEY
  doc.addPage();
  yPos = margin;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...PRIMARY_COLOR);
  doc.text("ANSWER KEY", margin, yPos);
  yPos += 15;
  doc.setFontSize(10);
  doc.setTextColor(...TEXT_COLOR);

  const renderKeySection = (title: string, items: any[], formatFn: (item: any, i: number) => string) => {
    if (items && items.length > 0) {
        checkPageBreak(20);
        doc.setFont("helvetica", "bold");
        doc.text(title, margin, yPos);
        yPos += 7;
        doc.setFont("helvetica", "normal");
        items.forEach((item, i) => {
            checkPageBreak(15);
            const str = formatFn(item, i);
            const split = doc.splitTextToSize(str, pageWidth - margin*2);
            doc.text(split, margin + 5, yPos);
            yPos += (split.length * 5) + 3;
        });
        yPos += 8;
    }
  };

  renderKeySection("I. Multiple Choice", testData.mcqs, (q, i) => `${i+1}. ${q.answer}`);
  renderKeySection("II. True/False", testData.trueFalse, (q, i) => `${i+1}. ${q.isTrue ? "True" : "False"}`);
  renderKeySection("III. Fill in Blanks", testData.fillInBlanks, (q, i) => `${i+1}. ${q.answer}`);
  
  if (testData.matching?.length > 0) {
      renderKeySection("IV. Matching Pairs", testData.matching[0].pairs, (q, i) => `${q.item} -> ${q.match}`);
  }

  renderKeySection("V. Short Answer Keys", testData.shortQuestions, (q, i) => `${i+1}. ${q.answerKey}`);
  renderKeySection("VI. Long Answer Keys", testData.longQuestions, (q, i) => `${i+1}. ${q.answerKey}`);
  renderKeySection("VII. Essay Key Points", testData.essays, (q, i) => `${i+1}. ${q.keyPoints}`);


  addWatermark();
  doc.save(`${(examName || testData.title || "Test").replace(/\s+/g, '_')}_StudyAI.pdf`);
};